### ISSUE TITLE
Error when trying to set up the integration

### ISSUE THREAD

**Issue by meranw38** [DeerMaximum/QR-Code-Generator#36]
Hi, I'm getting the following error after downloading your integration using HACS. 

**Error
Config flow could not be loaded: undefined**

Am I doing something wrong?

**Comment by DeerMaximum** [comment]
Can you see if there is anything in the logs of Home Assistant and send me the matching part?

**Comment by cooltings** [comment]
Have a similar problem where the config wizard is infinetly loading

**Comment by DeerMaximum** [comment]
@cooltings Can you see if there is anything in the logs of Home Assistant and send me the matching part?

**Comment by StefanRetief** [comment]
Here is the error that I can see in the logs:

```
Unexpected exception importing platform custom_components.qr_generator.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/qr_generator/__init__.py", line 10, in <module>
    PLATFORMS: list[str] = [Platform.IMAGE]
                            ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: IMAGE
```

**Comment by DeerMaximum** [comment]
For version 2.0.0 at least Home Assistant **2023.7** is required. Update your Home Assistant or use an older version of the integration.

**Comment by cooltings** [comment]
Ok thank you! Working now 😄
